# Just run `docker-compose up -d`. 

version: '3'
services:
  saowapan-web: 
    image: nginx:latest
    container_name: hb_front_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/usr/share/nginx/html
    ports:
      - 8080:80